-- Réguas de contato do followup, configuráveis pela Juliane.
--
-- Antes a cadência era `const RULES = [20, 60, 120]` no código da API: mudar
-- "falar de 20 em 20 dias" exigia deploy. Agora é dado.
--
-- E o cálculo da fila saiu do JavaScript para cá. A API buscava os 2.000 leads
-- mais recentes e TODOS os followups, e cruzava na memória — com 98.771 leads
-- isso significava calcular a fila sobre 2% da base, justamente os 2% mais
-- novos, que são os que ainda não venceram nenhuma régua. A tela ficava lenta
-- E mostrava o quadro errado.

create table if not exists followup_reguas (
  id         bigint generated by default as identity primary key,
  dias       integer not null unique check (dias > 0),
  rotulo     text,
  ativa      boolean not null default true,
  criada_em  timestamptz not null default now()
);

comment on table followup_reguas is
  'Cadência de contato do followup. Cada linha = "falar com o lead N dias depois de entrar".';

-- As três que estavam no código, para a tela não mudar de comportamento ao subir.
insert into followup_reguas (dias, rotulo) values
  (20,  'primeiro contato'),
  (60,  'segundo contato'),
  (120, 'terceiro contato')
on conflict (dias) do nothing;

alter table followup_reguas enable row level security;

-- Só o service_role (o admin fala com o banco por ele). Sem política para
-- anon/authenticated, então o app do cliente não vê nem escreve.
drop policy if exists followup_reguas_service on followup_reguas;
create policy followup_reguas_service on followup_reguas
  for all to service_role using (true) with check (true);

-- ───────────────────────────────────────────────────────── contagens da fila
-- Uma linha por régua e situação, contada no banco. É o que alimenta os
-- números do topo da tela sem trazer um único lead para a memória.
create or replace function followup_contagens()
returns table (dias integer, situacao text, quantos bigint)
language sql
stable
as $$
  with reguas as (
    select dias from followup_reguas where ativa
  ),
  vencidos as (
    select
      r.dias,
      -- Dias desde a entrada do lead, menos a régua: >0 atrasado, 0 hoje, -1 amanhã.
      (date_part('day', now() - l.created_at)::int - r.dias) as diferenca
    from wg_quiz_leads l
    cross join reguas r
    where l.created_at <= now() - make_interval(days => r.dias - 1)
      and not exists (
        select 1 from wg_lead_followups f
        where f.lead_id = l.id and f.rule_days = r.dias
      )
  )
  select
    dias,
    case when diferenca >= 1 then 'atrasados'
         when diferenca = 0  then 'hoje'
         else 'amanha' end as situacao,
    count(*) as quantos
  from vencidos
  group by 1, 2;
$$;

-- ─────────────────────────────────────────────────────────── página da fila
-- Devolve UMA página de cards. A tela pede mais conforme a pessoa rola, em vez
-- de receber dezenas de milhares de uma vez.
create or replace function followup_fila(
  p_situacao text,
  p_dias     integer default null,
  p_limite   integer default 50,
  p_offset   integer default 0
)
returns table (
  id           uuid,
  name         text,
  email        text,
  phone        text,
  utm_source   text,
  utm_campaign text,
  created_at   timestamptz,
  days_since   integer,
  rule_days    integer,
  days_overdue integer
)
language sql
stable
as $$
  with reguas as (
    select dias from followup_reguas
     where ativa and (p_dias is null or dias = p_dias)
  ),
  cards as (
    select
      l.id, l.name, l.email, l.phone, l.utm_source, l.utm_campaign, l.created_at,
      date_part('day', now() - l.created_at)::int as days_since,
      r.dias as rule_days,
      (date_part('day', now() - l.created_at)::int - r.dias) as diferenca
    from wg_quiz_leads l
    cross join reguas r
    where l.created_at <= now() - make_interval(days => r.dias - 1)
      and not exists (
        select 1 from wg_lead_followups f
        where f.lead_id = l.id and f.rule_days = r.dias
      )
  )
  select
    id, name, email, phone, utm_source, utm_campaign, created_at,
    days_since, rule_days,
    greatest(0, diferenca) as days_overdue
  from cards
  where case p_situacao
          when 'atrasados' then diferenca >= 1
          when 'hoje'      then diferenca = 0
          when 'amanha'    then diferenca = -1
          else true
        end
  -- Mais atrasado primeiro: é a ordem em que a Juliane quer atacar a fila.
  -- `id` no fim para a paginação não repetir nem pular linha em empate.
  order by diferenca desc, rule_days asc, id
  limit greatest(1, least(p_limite, 200))
  offset greatest(0, p_offset);
$$;

-- Total da base e quantos ainda não venceram nenhuma régua (o "aguardando").
create or replace function followup_resumo()
returns table (total_leads bigint, aguardando bigint)
language sql
stable
as $$
  select
    (select count(*) from wg_quiz_leads),
    (select count(*) from wg_quiz_leads l
      where l.created_at > now() - make_interval(
        days => (select coalesce(min(dias), 20) from followup_reguas where ativa)
      ));
$$;
