-- Cupons de desconto do Plano da Ju.
--
-- Até aqui o preço era uma constante no código (PLAN_BASE_CENTS = 3490) usada
-- pelo PIX e pelo cartão. Qualquer promessa de preço menor numa mensagem
-- levaria a cliente a um checkout cobrando 34,90 — reclamação e estorno certos.
--
-- ⚠️ O valor cobrado é SEMPRE recalculado no servidor a partir desta tabela. O
-- navegador manda o código do cupom, nunca o preço.

create table if not exists cupons (
  id          bigint generated by default as identity primary key,
  codigo      text not null unique,
  -- 'preco_final' cobra exatamente `valor_cents` (é o caso do "de 34,90 por
  -- 14,90": o valor é o combinado, e não uma conta que pode arredondar
  -- diferente do que a mensagem prometeu).
  -- 'percentual' desconta `valor_cents` por cento do preço cheio.
  tipo        text not null default 'preco_final' check (tipo in ('preco_final', 'percentual')),
  valor_cents integer not null check (valor_cents >= 0),
  descricao   text,
  ativo       boolean not null default true,
  expira_em   timestamptz,
  -- Um cupom vaza: alguém posta num grupo e a promoção vira o preço de tabela.
  -- O limite de usos é a trava.
  usos_max    integer,
  usos        integer not null default 0,
  criado_em   timestamptz not null default now()
);

comment on table cupons is
  'Cupons de desconto. O preço cobrado é recalculado no servidor a partir daqui — o cliente nunca manda valor.';
comment on column cupons.usos_max is
  'Limite de usos. Nulo = ilimitado. Existe porque cupom vaza e vira preço de tabela.';

create index if not exists idx_cupons_codigo_ativo on cupons (upper(codigo)) where ativo;

alter table cupons enable row level security;

-- Só o service_role (as rotas de checkout e o admin). O app do cliente não lê
-- a tabela: ele manda o código e o servidor responde se vale e por quanto.
drop policy if exists cupons_service on cupons;
create policy cupons_service on cupons
  for all to service_role using (true) with check (true);

-- Quem usou qual cupom. Serve para medir a campanha e para investigar abuso.
create table if not exists cupons_usos (
  id         bigint generated by default as identity primary key,
  cupom_id   bigint not null references cupons(id) on delete cascade,
  email      text,
  valor_cents integer not null,
  usado_em   timestamptz not null default now()
);
create index if not exists idx_cupons_usos_cupom on cupons_usos (cupom_id, usado_em desc);

alter table cupons_usos enable row level security;
drop policy if exists cupons_usos_service on cupons_usos;
create policy cupons_usos_service on cupons_usos
  for all to service_role using (true) with check (true);

/**
 * Consome um uso do cupom de forma atômica.
 *
 * Sem isto, duas compras simultâneas com o último uso disponível passariam as
 * duas: cada uma leria `usos < usos_max` antes de a outra gravar. O update
 * condicional resolve no próprio banco — quem chegar depois não encontra linha
 * e recebe zero.
 */
create or replace function cupom_consumir(p_codigo text)
returns table (id bigint, tipo text, valor_cents integer)
language sql
as $$
  update cupons c
     set usos = c.usos + 1
   where c.id = (
     select c2.id from cupons c2
      where upper(c2.codigo) = upper(p_codigo)
        and c2.ativo
        and (c2.expira_em is null or c2.expira_em > now())
        and (c2.usos_max is null or c2.usos < c2.usos_max)
      limit 1
     )
  returning c.id, c.tipo, c.valor_cents;
$$;
